### ISSUE TITLE
notebook kernel dies on zynq ultrascale

### ISSUE THREAD

**Issue by yunqu** [sfox14/pynq-ekf#8]
on zynq-ultrascale (ultra96 and zcu104), notebook kernel dies when calling hardware functions.

will need to look into it.

also, tag v2.3 has to change until the repo is fully tested.

**Comment by sfox14** [comment]
This will be difficult for me to fix since I don't have either of the ultrascale boards. Should be getting a zcu104 board before the end of the year though.

**Comment by yunqu** [comment]
ok, let me fix them then. z1 and z2 seem to work though

**Comment by yunqu** [comment]
Pull request #9  should make them work again. Just tested them on zcu104

feel free to close this issue after you merge that in.
